# Generated by Django 4.2.27 on 2026-02-15 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alerttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='classstable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_year', models.IntegerField(blank=True, help_text='Year when this batch of students joined (e.g., 2024)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='departmenttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logintable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('usertype', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='studenttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('admn_no', models.IntegerField(blank=True, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('Photo', models.FileField(blank=True, null=True, upload_to='profile_photos/students/')),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GateApp.logintable')),
                ('classs', models.ForeignKey(blank=True, help_text='The permanent batch this student belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='GateApp.classstable')),
            ],
        ),
        migrations.CreateModel(
            name='securitytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('Photo', models.FileField(blank=True, null=True, upload_to='profile_photos/security/')),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GateApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='mentortable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='profile_photos/mentors/')),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GateApp.logintable')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GateApp.departmenttable')),
            ],
        ),
        migrations.CreateModel(
            name='exitpasstable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, max_length=100, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('mentor_status', models.CharField(blank=True, max_length=100, null=True)),
                ('security_status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('qrcode', models.FileField(blank=True, null=True, upload_to='')),
                ('reject_reason', models.TextField(blank=True, null=True)),
                ('mentor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GateApp.mentortable')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GateApp.studenttable')),
            ],
        ),
        migrations.CreateModel(
            name='dept_assigntable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GateApp.departmenttable')),
                ('mentor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GateApp.mentortable')),
            ],
        ),
        migrations.CreateModel(
            name='complainttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(blank=True, max_length=200, null=True)),
                ('reply', models.TextField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GateApp.studenttable')),
            ],
        ),
        migrations.AddField(
            model_name='classstable',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GateApp.departmenttable'),
        ),
        migrations.CreateModel(
            name='class_assigntable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(blank=True, help_text='The batch this mentor is responsible for', null=True, on_delete=django.db.models.deletion.CASCADE, to='GateApp.classstable')),
                ('mentor_id', models.ForeignKey(blank=True, help_text='The mentor assigned to manage this batch', null=True, on_delete=django.db.models.deletion.CASCADE, to='GateApp.mentortable')),
            ],
        ),
        migrations.CreateModel(
            name='MentorDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='GateApp.mentortable')),
            ],
            options={
                'verbose_name': 'Mentor Device Token',
                'verbose_name_plural': 'Mentor Device Tokens',
                'unique_together': {('mentor', 'device_token')},
            },
        ),
    ]
