# Generated by Django 4.2.27 on 2026-01-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exitpasstable',
            name='date',
        ),
    ]
