# Generated by Django 4.2.27 on 2026-02-15 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitpasstable',
            name='is_group_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='class_assigntable',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GateApp.classstable'),
        ),
        migrations.AlterField(
            model_name='class_assigntable',
            name='mentor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GateApp.mentortable'),
        ),
        migrations.AlterField(
            model_name='classstable',
            name='admission_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='classs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GateApp.classstable'),
        ),
    ]
