# Generated by Django 4.2 on 2026-04-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitpasstable',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='mentortable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/mentors/'),
        ),
        migrations.AlterField(
            model_name='securitytable',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/security/'),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/students/'),
        ),
    ]
