# Generated by Django 4.2 on 2026-07-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0002_alter_exitpasstable_qrcode_alter_mentortable_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitpasstable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='exitpasstable',
            name='is_group_pass',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='exitpasstable',
            name='security_status',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='admn_no',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
