# Generated by Django 4.2.27 on 2026-02-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0002_exitpasstable_is_group_pass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
