# Generated by Django 4.2.27 on 2026-01-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0002_remove_exitpasstable_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitpasstable',
            name='qrcode',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
