# Generated by Django 4.2.27 on 2026-02-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0003_alter_logintable_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitpasstable',
            name='mentor_status',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logintable',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
