# Generated by Django 4.2 on 2026-07-14 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0003_add_db_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitpasstable',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_passes', to='GateApp.securitytable'),
        ),
    ]
