# Generated by Django 4.2.27 on 2026-01-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0003_exitpasstable_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitpasstable',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
