# Generated by Django 4.2.27 on 2026-02-18 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0004_alter_exitpasstable_mentor_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hodtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('LOGINID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GateApp.logintable')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GateApp.departmenttable')),
            ],
        ),
    ]
