# Generated by Django 4.2.27 on 2026-01-16 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0004_alter_exitpasstable_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainttable',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
