# Generated by Django 4.2.27 on 2026-01-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0005_alter_complainttable_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttable',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
