# Generated by Django 4.2.27 on 2026-02-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0005_hodtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodtable',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/hod/'),
        ),
        migrations.AddField(
            model_name='hodtable',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hodtable',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
