# Generated by Django 4.2.27 on 2026-01-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0006_studenttable_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentortable',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
