# Generated by Django 4.2.27 on 2026-02-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0006_hodtable_image_hodtable_name_hodtable_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hodtable',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hodtable',
            name='phone',
        ),
    ]
