# Generated by Django 4.2.27 on 2026-02-21 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0007_remove_hodtable_image_remove_hodtable_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hodtable',
        ),
    ]
