# Generated by Django 4.2.27 on 2026-01-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0007_mentortable_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitpasstable',
            name='approved_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='exitpasstable',
            name='scanned_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
