# Generated by Django 4.2.27 on 2026-01-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0008_alter_exitpasstable_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitpasstable',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exitpasstable',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
