# Generated by Django 4.2.27 on 2026-03-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0008_delete_hodtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alerttable',
        ),
    ]
