# Generated by Django 4.2.27 on 2026-01-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0009_alter_exitpasstable_approved_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complainttable',
            old_name='message',
            new_name='complaint',
        ),
    ]
