# Generated by Django 4.2.27 on 2026-01-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0010_rename_message_complainttable_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complainttable',
            name='status',
        ),
    ]
