# Generated by Django 4.2.27 on 2026-01-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0011_remove_complainttable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitpasstable',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
