# Generated by Django 4.2.27 on 2026-01-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0013_exitpasstable_mentor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttable',
            old_name='image',
            new_name='Photo',
        ),
        migrations.CreateModel(
            name='LogTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attendance', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('STUDENTID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GateApp.studenttable')),
            ],
        ),
    ]
