# Generated by Django 4.2.27 on 2026-01-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0014_rename_image_studenttable_photo_logtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtable',
            name='Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
