# Generated by Django 4.2.27 on 2026-01-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0015_logtable_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitytable',
            name='Photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
