# Generated by Django 4.2.27 on 2026-01-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0016_securitytable_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogTable',
        ),
    ]
