# Generated by Django 4.2.27 on 2026-01-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0017_delete_logtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentortable',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/mentors/'),
        ),
        migrations.AlterField(
            model_name='securitytable',
            name='Photo',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/security/'),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='Photo',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/students/'),
        ),
    ]
