# Generated by Django 4.2.27 on 2026-01-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0018_alter_mentortable_image_alter_securitytable_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitpasstable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
