# Generated by Django 4.2.27 on 2026-01-31 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0019_alter_exitpasstable_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='GateApp.mentortable')),
            ],
            options={
                'verbose_name': 'Mentor Device Token',
                'verbose_name_plural': 'Mentor Device Tokens',
                'unique_together': {('mentor', 'device_token')},
            },
        ),
    ]
