# Generated by Django 4.2.27 on 2026-02-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GateApp', '0021_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentortable',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securitytable',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
